DROP TABLE IF EXISTS USERS;  
CREATE TABLE USERS (  
U_Id INT AUTO_INCREMENT  PRIMARY KEY,  
Full_Name VARCHAR(50) NOT NULL,  
Password VARCHAR(50) NOT NULL, 
ADDRESS VARCHAR(100) NOT NULL,
CONTACT_NO VARCHAR(12) NOT NULL,
e_mail VARCHAR(50) NOT NULL,
DL_NO VARCHAR(12) NOT NULL
);   